version: '3.7'
services:
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - "./minio-data:/data"
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
